# Build website and save it on gh-pages branch
name: build-and-save-website

# Only run this when the main branch is changed
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

# This job installs dependencies, builds the website and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the site
        run: |
          cd docs
          sphinx-build -nW --keep-going -b html .  _build

      # If we've pushed to main, push the book's HTML to github-pages
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Save to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
          # # set it to a subfolder of the root to keep all PR previews:
          # destination_dir: latest
          # cname: website.com
      - if: ${{ github.event_name == 'pull_request' }}
        name: Save to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          # # create a version for an PR
          # # will be automatically deleted in case the build in on the root
          destination_dir: pr-${{ github.event.number }}
